apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderflow-api
spec:
  replicas: 2
  minReadySeconds: 39
  selector:
    matchLabels:
      app: orderflow-api
  template:
    metadata:
      labels:
        app: orderflow-api
    spec:
      containers:
        - name: orderflow-api
          image: orderflow-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: orderflow-config
            - secretRef:
                name: orderflow-secret
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold:  3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 3
            failureThreshold: 10
